Bugfix: reset password SQL was failing
due to:

PSQLException: Cannot change transaction isolation level in the middle
of a transaction

See:

https://shipreq.freshdesk.com/a/tickets/60